my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: GCP_PROJECT_ID
      dataset: DBT_DATASET_NAME
      threads: 4 
      OPTIONAL_CONFIG: VALUE

      # These fields come from the service account json keyfile
      keyfile_json:
        project_id: "{{ env_var('snowflake_account') }}"
        private_key: "{{ env_var('snowflake_account') }}"
        client_email: "{{ env_var('snowflake_account') }}"
        token_uri: "{{ env_var('snowflake_account') }}"


